// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// upperTmat
arma::vec upperTmat(const arma::mat mat);
RcppExport SEXP _selectioncorrelatedgenotypes_upperTmat(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(upperTmat(mat));
    return rcpp_result_gen;
END_RCPP
}
// Xmvcenter
arma::mat Xmvcenter(arma::mat X);
RcppExport SEXP _selectioncorrelatedgenotypes_Xmvcenter(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(Xmvcenter(X));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_selectioncorrelatedgenotypes_upperTmat", (DL_FUNC) &_selectioncorrelatedgenotypes_upperTmat, 1},
    {"_selectioncorrelatedgenotypes_Xmvcenter", (DL_FUNC) &_selectioncorrelatedgenotypes_Xmvcenter, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_selectioncorrelatedgenotypes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
