# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

upperTmat <- function(mat) {
    .Call('_selectioncorrelatedgenotypes_upperTmat', PACKAGE = 'selectioncorrelatedgenotypes', mat)
}

Xmvcenter <- function(X) {
    .Call('_selectioncorrelatedgenotypes_Xmvcenter', PACKAGE = 'selectioncorrelatedgenotypes', X)
}

